CREATE TABLE animal (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    especie VARCHAR(255) NOT NULL,
    nome_provisorio VARCHAR(255) NOT NULL,
    idade_estimada INT NOT NULL,
    raca VARCHAR(255) NOT NULL,
    data_entrada date NOT NULL,
    data_saida date,
    condicoes_chegada VARCHAR(255) NOT NULL,
    nome_recebedor VARCHAR(255) NOT NULL,
    data_obito date,
    porte VARCHAR(255) NOT NULL,
    data_adocao date,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);