server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
    mongodb:
      uri: mongodb://root:example@127.0.0.1:27017/mongo?authSource=admin&retryWrites=true&w=majority
      database: cliente
      auto-index-creation: true

application-version: 1.0
